name: List Changed Files

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

     - name: Get changed files
       id: changed-files
       uses: tj-actions/changed-files@v35
       with:
         files: |
           my-file.txt
           *.sh
           *.png
           !*.md
           test_directory
           **/*.sql
