name: List changed files in PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
     - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

     - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
      
      #- name: List changed files
       # run: |
        #  CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        #  echo "Changed files: $CHANGED_FILES"
